{
 "title": "Windows Server Telemetry",
 "description": "A single pane of glass for viewing simple Windows server metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "label": "Server Name" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{instance=~\"$server\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((windows_memory_available_bytes{instance=~\"$server\"} / windows_memory_physical_total_bytes{instance=~\"$server\"}) * 100)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((windows_logical_disk_free_bytes{instance=~\"$server\", volume=~\"[A-Z]:\"} / windows_logical_disk_size_bytes{instance=~\"$server\", volume=~\"[A-Z]:\"}) * 100)",
     "legendFormat": "{{volume}} Drive Utilization (%)"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(windows_logical_disk_write_latency_seconds_total{instance=~\"$server\", volume=~\"[A-Z]:\"}[5m]) / rate(windows_logical_disk_writes_total{instance=~\"$server\", volume=~\"[A-Z]:\"}[5m])) * 1000",
     "legendFormat": " {{volume}} Drive Write Latency"
    }
   ]
  },
  {
   "title": "Handle Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_process_handles{instance=~\"$server\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{instance=~\"$server\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((windows_logical_disk_free_bytes{instance=~\"$server\", volume=~\"[A-Z]:\"} / windows_logical_disk_size_bytes{instance=~\"$server\", volume=~\"[A-Z]:\"}) * 100)",
     "legendFormat": "{{volume}} Drive Utilization (%)"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(windows_logical_disk_write_latency_seconds_total{instance=~\"$server\", volume=~\"[A-Z]:\"}[5m]) / rate(windows_logical_disk_writes_total{instance=~\"$server\", volume=~\"[A-Z]:\"}[5m])) * 1000",
     "legendFormat": " {{volume}} Drive Write Latency"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((windows_memory_available_bytes{instance=~\"$server\"} / windows_memory_physical_total_bytes{instance=~\"$server\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-paged Memory Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "windows_memory_pool_nonpaged_bytes{instance=~\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handle Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(windows_process_handles{instance=~\"$server\"})",
     "legendFormat": " Handles"
    }
   ]
  }
 ]
}